#!/bin/sh

scripts/setup_common.py --full-name="Arndale Board" \
                        --cross-compile="arm-sony-linux-gnueabi-" \
                        --arch-name="arm" \
                        --target-name="arndale" \
                        --fixup-kernel-headers="scripts/kernel_headers/default.fixup" \
                        --defconfig-base="arch/arm/configs/arndale_defconfig" \
                        --build-instruction="make" \
                        --image="arch/arm/boot/uImage" \
                        "$@"
