#!/bin/sh

scripts/setup_common.py --full-name="zc702" \
                        --cross-compile="arm-linux-gnueabihf-" \
                        --arch-name="arm" \
                        --target-name="zc702" \
                        --fixup-kernel-headers="scripts/kernel_headers/default.fixup" \
                        --defconfig-base="arch/arm/configs/zc702-smp_defconfig" \
                        --build-instruction="make" \
                        --image="arch/arm/boot/uImage" \
                        "$@"
