#!/bin/sh

scripts/setup_common.py --full-name="PC x86_64" \
                        --cross-compile="" \
                        --arch-name="x86" \
                        --target-name="pc-x86-64" \
                        --fixup-kernel-headers="scripts/kernel_headers/default.fixup" \
                        --defconfig-base="arch/x86/configs/setup-generic-pc-x86-64-min" \
                        --build-instruction="make" \
                        --image="arch/x86/boot/bzImage" \
                        "$@"
